# Generated by Django 5.1.5 on 2026-01-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_room_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='form_type',
            field=models.CharField(db_index=True, default='booking', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Deluxe Room', 'Deluxe Room'), ('Luxury Villa', 'Luxury Villa'), ('Premium Cottage', 'Premium Cottage')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='safari_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('5-star', '5-Star'), ('4-star', '4-Star'), ('3-star', '3-Star')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['form_type', 'created_at'], name='myapp_booki_form_ty_2ce90a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['email', 'created_at'], name='myapp_booki_email_50bd44_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['type'], name='myapp_hotel_type_cceb94_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['name'], name='myapp_hotel_name_63b041_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['location'], name='myapp_hotel_locatio_aca6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['type', 'location'], name='myapp_hotel_type_94f6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'availability'], name='myapp_room_hotel_i_778810_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'room_type'], name='myapp_room_hotel_i_b0ca4d_idx'),
        ),
    ]
